[package]
name = "passwd-derive"
version = "0.1.1"
readme = "readme.md"
description = "Deterministic password generator"
license = "MIT OR Apache-2.0"
repository = "https://github.com/greekfetacheese/no-pass-plz"
edition = "2024"

[dependencies]
argon2-rs = "0.2"
hmac = "0.12.1"
sha3 = "0.10.8"
secure-types = "0.3"
hex = "0.4.3"