[package]
name = "passwd-derive"
version = "0.1.2"
readme = "readme.md"
description = "Deterministic password generator"
license = "MIT OR Apache-2.0"
repository = "https://github.com/greekfetacheese/no-pass-plz"
edition = "2024"

[dependencies]
argon2-rs = "0.2"
hmac = {version = "0.13.0", features = ["zeroize"]}
sha3 = "0.12"
secure-types = "0.3"
hex = "0.4"