[workspace]
members = ["crates/passwd-derive"]
resolver = "2"

[package]
name = "no-pass-plz"
version = "2.0.20"
edition = "2024"

[dependencies]

# GUI
eframe = {version = "0.36", features = ["wgpu"]}
egui_extras = { version = "0.36", features = ["image"] }
egui_commonmark = "0.25"
egui-elements = {version = "1", features = ["secure-types", "qr-image", "qr-scanner"]}

passwd-derive = { path = "crates/passwd-derive" }
argon2-rs = "0.2"

# Misc
secure-types = "0.3"
lazy_static = "1.5"
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[profile.prod]
inherits = "release"
codegen-units = 1
incremental = true
strip = true
opt-level = 2
debug = false
lto = "fat"

[features]
dev = []